# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TEBounds' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TEBounds
	pod 'CCZoomTransition', '~> 0.1.1'
end
