# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'CCGitHubPro' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CCGitHubPro
	pod 'GDPerformanceView', '~> 1.1.0'
	pod 'SnapKit', '~> 3.0.2'
end
