# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TEAgora' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TEAgora
	pod 'AgoraRtcEngineKit', :git => 'https://github.com/SecretLisa/AgoraRtcEngineKit', :commit => 'e878a8a4aadd5d915ff5b69871c8d69c01ab2587'
end
